version: "3"

services:

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    working_dir: /frontend
    stdin_open: true
    restart: always

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - 8181:8080
    working_dir: /backend
    environment:
      DB_HOST_NAME: storage
      SPRING_PROFILES_ACTIVE: container
    depends_on:
      - storage
    restart: always

  storage:
    container_name: storage
    build: ./storage
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: answerium
    ports:
      - 5432:5432
    restart: always

volumes:
  postgres-volume:
